emphysema/patients/controller.py
from flask import Blueprint, render_template, flash, redirect, url_for, request
from flask_login import login_required

from emphysema import db
from emphysema.diseases.model import Disease, DiseaseToPatient
from emphysema.diseases.manager import DiseaseService
from emphysema.patients.facade import PatientFacade
from emphysema.patients.froms import PatientForm
from emphysema.patients.model import Patient
from emphysema.patients.manager import PatientService
from emphysema.results.service import get_result_for_patient, get_results
from emphysema.services.utils import getIdFromUrl
from emphysema.services.crudService import BaseService
from emphysema.symptoms.model import Symptom, SymptomToPatient
from emphysema.symptoms.manager import SymptomService

patientsBp = Blueprint('patientsBp', __name__)

patientsService = PatientService()
diseaseService = DiseaseService()
symptomService = SymptomService()
baseService = BaseService()
patientFacade = PatientFacade()


@patientsBp.route('/patients')
@login_required
def patients():
    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per_page', 20, type=int)
    patients = patientsService.get_paged_patients(page=page, per_page=per_page)
    return render_template("patient/patients.html", title="Pacienti", patients=patients)


@patientsBp.route('/patient/<id>')
@login_required
def patient(id):
    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per_page', 20, type=int)
    patient_detail = patientsService.get_by_id(class_=Patient, id=getIdFromUrl(id))
    results = get_result_for_patient(id, page, per_page)
    return render_template("patient/patient.html", title="Pacienti", patient=patient_detail, results=results)


@patientsBp.route('/patient/resultPaged')
@login_required
def pagedResultsForPatient():
    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per_page', 20, type=int)
    results = get_results(page, per_page)
    return render_template("result/resultsForPaginationOnPatient.html", results=results)


@patientsBp.route('/registerNewPatient', methods=['GET', 'POST'])
@login_required
def registerNewPatient():
    form = PatientForm()
    if form.validate_on_submit():
        patientFacade.crete_new_patient(form=form)
        flash(f'Pacient {form.nameOfPatient.data} vytvořen úspěšně', 'success')
        return redirect(url_for('patientsBp.patients'))
    patientFacade.populate_data_for_form_register(form=form)
    return render_template("patient/registerNewPatient.html",
                           title="Registrace nového pacienta",
                           form=form,
                           button="Vytvořit uživatele",
                           legend="Nový pacient"
                           )


@patientsBp.route('/registerNewPatient/<id>', methods=['GET', 'POST'])
@login_required
def updatePatient(id):
    form = PatientForm()
    if form.validate_on_submit():
        patientFacade.update_patient(form=form,id=getIdFromUrl(id))
        flash(f'Pacient {form.nameOfPatient.data} aktualizován úspěšně', 'success')
        return redirect(url_for('patientsBp.patients'))

    patientFacade.populate_data_for_form_update(form=form,id=getIdFromUrl(id))
    patientFacade.populate_data_for_form_register(form=form)
    return render_template("patient//registerNewPatient.html",
                           title="Aktualizace pacienta",
                           form=form,
                           button="Aktualizovat uživatele",
                           legend="Aktualizace pacienta")


@patientsBp.route('/removePatient/<id>')
@login_required
def remove_patient(id):
    patientsService.remove(getIdFromUrl(id))
    flash(f'Pacient úspěšně smazán', 'success')
    return redirect(url_for('patientsBp.patients'))

emphysema/results/controller.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_required

from emphysema.diseases.manager import DiseaseService
from emphysema.patients.facade import PatientFacade
from emphysema.patients.manager import PatientService
from emphysema.patients.model import Patient
from emphysema.results.facade import ResultFacade
from emphysema.results.froms import SendToPredictionExpertSystem, SendToPredcitionForm
from emphysema.results.service import get_results, get_x_ray_to_result
from emphysema.services.crudService import BaseService
from emphysema.services.utils import getIdFromUrl, getNameFromUrl
from emphysema.symptoms.manager import SymptomService

resultsBp = Blueprint('resultsBp', __name__)

baseService = BaseService()
patientsService = PatientService()
diseaseService = DiseaseService()
symptomService = SymptomService()
resultFacade = ResultFacade()
patientFacade = PatientFacade()


@resultsBp.route('/results')
@login_required
def results():
    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per_page', 20, type=int)
    results_paged = get_results(page, per_page)
    return render_template("result/results.html", title="Výsledky", results=results_paged)


@resultsBp.route('/result_x_ray/<id>')
@login_required
def result_x_ray(id):
    result = get_x_ray_to_result(id=id)
    if result.generatedName:
        path_to_xray = '/static/x_rays/' + result.generatedName
        return render_template("result/x_ray.html", image=path_to_xray, old_image_name=result.originalName)
    else:
        return render_template("result/no_x_ray_image.html")


@resultsBp.route('/sendToPrediction/<id>', methods=['GET', 'POST'])
@login_required
def send_to_prediction(id):
    patient_id = getIdFromUrl(id)
    form = SendToPredcitionForm(patient_id=patient_id)
    patient = baseService.get_by_id(Patient, patient_id)
    if form.validate_on_submit():
        result = resultFacade.send_to_prediction(form=form, id=patient_id)
        if result:
            return redirect(url_for('patientsBp.patient', id=patient_id))
        else:
            flash(f'Pacient {patient.nameOfPatient} nebyl úspěšně odeslán k predikci', 'danger')
            return redirect(url_for('patientsBp.patient', id=patient_id))
    return render_template("prediction/sendToPrediction.html", title="Predikce", form=form,
                           patient_id=getNameFromUrl(id)[1], nameOfPatient=patient.nameOfPatient)


@resultsBp.route('/sendToPredictionExpertSystem/<id>', methods=['GET', 'POST'])
@login_required
def send_to_prediction_expert_system(id):
    idFromUrl = getIdFromUrl(id)
    form = SendToPredictionExpertSystem()
    patient = baseService.get_by_id(class_=Patient, id=idFromUrl)
    if form.validate_on_submit():
        patientFacade.update_patient(form=form, id=getIdFromUrl(id))
        resultFacade.send_to_prediction_expert_system(patient=patient, id=idFromUrl, form=form)
        flash(f'Pacient {form.nameOfPatient.data} byl úspěšně odeslán k predikci', 'success')
        return redirect(url_for('patientsBp.patient', id=idFromUrl))
    resultFacade.prepare_data_for_form(form=form, id=idFromUrl, patient=patient)
    return render_template("prediction/sendToPredictionExpertSystem.html",
                           title="Predikce pomoci expertního systému a NS",
                           form=form, patient_id=idFromUrl)

emphysema/templates/result/no_x_ray_image.html
<div id="imgXray" class="alert alert-warning">
    Pro danou predikci nebyl dodán obrázek
</div>

emphysema/templates/result/results.html
{% extends "layout.html" %}


{% block content %}
    <section class="w-75 m-auto pt-3">
        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">ID</th>
                <th scope="col">Jméno pacienta</th>
                <th scope="col">Výsledky z NS</th>
                <th scope="col">Výsledky z ES</th>
                <th scope="col">Datum vzniku</th>
                <th scope="col">Datum ukončeni predikce</th>
                <th scope="col">Akce</th>
            </tr>
            </thead>
            <tbody>
            {% for result,patient in results.items %}
                <tr>
                    <th scope="row">{{ loop.index }}</th>
                    <th scope="row" id="id">{{ result.id }}</th>
                    <td>{{ patient.nameOfPatient }}</td>
                    <td>{{ result.emphysemaNN }}</td>
                    <td>{{ result.emphysemaES }}</td>
                    <td>{{ result.dateOfCreation }}</td>
                    <td>{{ result.dateOfEnd }}</td>
                    <td class="">
                        <a href="patient/{{ result.patient_id }}"
                           class="bi bi-info-square icons"></a>
                    </td>
                </tr>
            {% endfor %}

            </tbody>
        </table>

    </section>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if results.prev_num %}
                <li class="page-item disabled">
                    <a class="page-link" href="{{ url_for('resultsBp.results',page=results.prev_num) }}"
                       tabindex="-1">Previous</a>
                </li>
            {% endif %}

            {% for page_number in results.iter_pages() %}
                {% if page_number and results.pages != 1 %}
                    {% if results.page == page_number %}
                        <li class="page-item">
                            <a class="page-link active"
                               href="{{ url_for('resultsBp.results',page=page_number) }}">{{ page_number }}</a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link"
                               href="{{ url_for('resultsBp.results',page=page_number) }}">{{ page_number }}</a>
                        </li>
                    {% endif %}
                {% endif %}
            {% endfor %}

            {% if results.next_num %}
                <li class="page-item">
                    <a class="page-link" href="{{ url_for('resultsBp.results',page=results.next_num) }}">Next</a>
                </li>
            {% endif %}
        </ul>
    </nav>


{% endblock %}

emphysema/templates/result/resultsForPaginationOnPatient.html
<section class="w-75 m-auto pt-3" id="results">
    <div class="own"></div>
    <table id="resultsTable" class="table table-striped">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">ID</th>
            <th scope="col">Jméno pacienta</th>
            <th scope="col">Výsledky z NS</th>
            <th scope="col">Výsledky z ES</th>
            <th scope="col">Datum vzniku</th>
            <th scope="col">Datum ukončeni predikce</th>
            <th scope="col">Akce</th>
        </tr>
        </thead>
        <tbody>
        {% if results.items %}
            {% for result,patientOfResult in results.items %}
                <tr>
                    <th scope="row">{{ loop.index }}</th>
                    <th scope="row" id="id">{{ result.id }}</th>
                    <td>{{ patientOfResult.nameOfPatient }}</td>
                    <td>{{ result.emphysemaNN }}</td>
                    <td><pre>{{ result.emphysemaES }}</pre></td>
                    <td>{{ result.dateOfCreation }}</td>
                    <td>{{ result.dateOfEnd }}</td>
                    <td class="">
                        <a id="xRayModalGet" class="bi bi-info-square icons" type="button" data-val="{{ result.id }}" data-bs-toggle="modal" data-bs-target="#xRayModal"></a>
                    </td>
                </tr>
            {% endfor %}
        {% else %}
            <td colspan="8" class="w-100 text-muted text-center">Nebyly nalezeny žádné výsledky</td>
        {% endif %}

        </tbody>
    </table>
    <!-- Modal -->
    <div class="modal fade" id="xRayModal" tabindex="-1" aria-labelledby="xRayModal" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="xRayModal">RTG snímek odeslaný k predikci</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                        {% include "result/x_ray.html" %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Zavřít</button>
                </div>
            </div>
        </div>
    </div>


    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if results.prev_num %}
                <li class="page-item">
                    <a class="page-link pagedResultsOnPacient"
                       href="{{ url_for('patientsBp.pagedResultsForPatient',page=results.prev_num) }}"
                       tabindex="-1">Previous</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link pagedResultsOnPacient"
                       href="{{ url_for('patientsBp.pagedResultsForPatient',page=results.prev_num) }}"
                       tabindex="-1">Previous</a>
                </li>
            {% endif %}

            {% for page_number in results.iter_pages() %}
                {% if page_number and results.pages != 1 %}
                    {% if results.page == page_number %}
                        <li class="page-item active">
                            <a class="page-link pagedResultsOnPacient"
                               href="{{ url_for('patientsBp.pagedResultsForPatient',page=page_number) }}">{{ page_number }}</a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link pagedResultsOnPacient"
                               href="{{ url_for('patientsBp.pagedResultsForPatient',page=page_number) }}">{{ page_number }}</a>
                        </li>
                    {% endif %}
                {% endif %}
            {% endfor %}

            {% if results.next_num %}
                <li class="page-item">
                    <a class="page-link pagedResultsOnPacient"
                       href="{{ url_for('patientsBp.pagedResultsForPatient',page=results.next_num) }}">Next</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link pagedResultsOnPacient"
                       href="{{ url_for('patientsBp.pagedResultsForPatient',page=results.next_num) }}">Next</a>
                </li>
            {% endif %}
        </ul>
    </nav>
</section>

emphysema/templates/result/x_ray.html
<img id="imgXray" src="{{ image }}" class="img-fluid" alt="{{ old_image_name }}" >