emphysema/patients/controller.py
from flask import Blueprint, render_template, flash, redirect, url_for, request
from flask_login import login_required

from emphysema import db
from emphysema.diseases.model import Disease, DiseaseToPatient
from emphysema.diseases.manager import DiseaseService
from emphysema.patients.facade import PatientFacade
from emphysema.patients.froms import PatientForm
from emphysema.patients.model import Patient
from emphysema.patients.manager import PatientService
from emphysema.results.service import get_result_for_patient, get_results
from emphysema.services.utils import getIdFromUrl
from emphysema.services.crudService import BaseService
from emphysema.symptoms.model import Symptom, SymptomToPatient
from emphysema.symptoms.manager import SymptomService

patientsBp = Blueprint('patientsBp', __name__)

patientsService = PatientService()
diseaseService = DiseaseService()
symptomService = SymptomService()
baseService = BaseService()
patientFacade = PatientFacade()


@patientsBp.route('/patients')
@login_required
def patients():
    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per_page', 20, type=int)
    patients = patientsService.get_paged_patients(page=page, per_page=per_page)
    return render_template("patient/patients.html", title="Pacienti", patients=patients)


@patientsBp.route('/patient/<id>')
@login_required
def patient(id):
    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per_page', 20, type=int)
    patient_detail = patientsService.get_by_id(class_=Patient, id=getIdFromUrl(id))
    results = get_result_for_patient(id, page, per_page)
    return render_template("patient/patient.html", title="Pacienti", patient=patient_detail, results=results)


@patientsBp.route('/patient/resultPaged')
@login_required
def pagedResultsForPatient():
    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per_page', 20, type=int)
    results = get_results(page, per_page)
    return render_template("result/resultsForPaginationOnPatient.html", results=results)


@patientsBp.route('/registerNewPatient', methods=['GET', 'POST'])
@login_required
def registerNewPatient():
    form = PatientForm()
    if form.validate_on_submit():
        patientFacade.crete_new_patient(form=form)
        flash(f'Pacient {form.nameOfPatient.data} vytvořen úspěšně', 'success')
        return redirect(url_for('patientsBp.patients'))
    patientFacade.populate_data_for_form_register(form=form)
    return render_template("patient/registerNewPatient.html",
                           title="Registrace nového pacienta",
                           form=form,
                           button="Vytvořit uživatele",
                           legend="Nový pacient"
                           )


@patientsBp.route('/registerNewPatient/<id>', methods=['GET', 'POST'])
@login_required
def updatePatient(id):
    form = PatientForm()
    if form.validate_on_submit():
        patientFacade.update_patient(form=form,id=getIdFromUrl(id))
        flash(f'Pacient {form.nameOfPatient.data} aktualizován úspěšně', 'success')
        return redirect(url_for('patientsBp.patients'))

    patientFacade.populate_data_for_form_update(form=form,id=getIdFromUrl(id))
    patientFacade.populate_data_for_form_register(form=form)
    return render_template("patient//registerNewPatient.html",
                           title="Aktualizace pacienta",
                           form=form,
                           button="Aktualizovat uživatele",
                           legend="Aktualizace pacienta")


@patientsBp.route('/removePatient/<id>')
@login_required
def remove_patient(id):
    patientsService.remove(getIdFromUrl(id))
    flash(f'Pacient úspěšně smazán', 'success')
    return redirect(url_for('patientsBp.patients'))

emphysema/templates/patient/patient.html
{% extends "layout.html" %}
{% block content %}
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category,message in messages %}
                <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}

    <div class="w-50 m-auto mt-5">

        <legend class="border-bottom mb-4">Pacient</legend>
        <div class="form-group">
            <label class="form-control-label" for="nameOfPatient">Jméno pacienta</label>

            <input class="form-control form-control-lg" id="nameOfPatient" name="nameOfPatient" disabled="" type="text"
                   value="{{ patient.nameOfPatient }}">

        </div>
        <div class="form-group">
            <label class="form-control-label" for="height">Výška</label>

            <input class="form-control form-control-lg" id="height" name="height" disabled="" step="1"
                   value="{{ patient.height }}">

        </div>
        <div class="form-group">
            <label class="form-control-label" for="weight">Váha</label>

            <input class="form-control form-control-lg" id="weight" name="weight" disabled="" step="1"
                   value="{{ patient.weight }}">

        </div>
        <div class="form-group">
            <label class="form-control-label" for="age">Věk</label>

            <input class="form-control form-control-lg" id="age" name="age" disabled="" step="1"
                   value="{{ patient.age }}">

        </div>
        <div class="form-group mt-3 mb-3">
            <label class="form-control-label" for="smoker">Kuřák</label>
            {% if patient.smoker %}
                <input class="form-check form-check-lg" id="smoker" name="smoker" type="checkbox" disabled=""
                       checked="{{ patient.smoker }}">
            {% else %}
                <input class="form-check form-check-lg" id="smoker" name="smoker" type="checkbox" disabled="">
            {% endif %}
        </div>
        <div class="form-group">
            <label class="form-control-label" for="weight">Krabičkoroky (Krabičky za den * roky jak dlouho
                kouří)</label>

            <input class="form-control form-control-lg" id="weight" name="weight" disabled="" step="1"
                   value="{{ patient.cigarets_per_year if patient.cigarets_per_year else "" }}">

        </div>
        <div class="form-group">
            <label class="form-control-label" for="breath_frequency">Dechová frekvence (počet dechů za minutu)</label>

            <input class="form-control form-control-lg" id="breath_frequency" name="breath_frequency" disabled=""
                   step="1"
                   value="{{ patient.breath_frequency if patient.breath_frequency else "" }}">

            <div id="collapsingAdvancedMenu" class="btn btn-outline-info">Zobrazit pokročilé nastavení</div>
            <div class="advancedMenu" style="display: none">
                <div class="form-group">
                    <label class="form-control-label" for="ptf_fev1">FEV1 (v litrech)</label>

                    <input class="form-control form-control-lg" id="ptf_fev1" name="ptf_fev1" disabled="" step="1"
                           value="{{ patient.ptf_fev1 if patient.ptf_fev1 else "" }}">

                </div>
                <div class="form-group">
                    <label class="form-control-label" for="ptf_fcv">FCV (v litrech)</label>

                    <input class="form-control form-control-lg" id="ptf_fcv" name="ptf_fcv" disabled="" step="1"
                           value="{{ patient.ptf_fcv if patient.ptf_fcv else "" }}">

                </div>
                <div class="form-group">
                    <label class="form-control-label" for="ptf_dlco">DLCO</label>

                    <input class="form-control form-control-lg" id="ptf_dlco" name="ptf_dlco" disabled="" step="1"
                           value="{{ patient.ptf_dlco if patient.ptf_dlco else "" }}">

                </div>
                <div class="form-group">
                    <label class="form-control-label" for="deficit_alfa_1">Deficit alfa-1-antitrypsináza</label>
                    {% if patient.deficit_alfa_1 %}
                        <input class="form-check form-check-lg" id="deficit_alfa_1" name="deficit_alfa_1"
                               type="checkbox"
                               disabled=""
                               checked="{{ patient.deficit_alfa_1 }}">
                    {% else %}
                        <input class="form-check form-check-lg" id="deficit_alfa_1" name="deficit_alfa_1"
                               type="checkbox" disabled="">
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="form-group w-45">
                <label class="form-control-label" for="otherDiseases">Jine nemoci</label>

                <select class="form-select form-control-lg h-15em" multiple disabled>
                    {% for d in patient.otherDiseases %}
                        <option value="{{ d.disease_id }}">{{ d.disease_id }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group w-45">
                <label class="form-control-label" for="otherDiseases">Symptomy</label>

                <select class="form-select form-control-lg h-15em" multiple disabled>
                    {% for s in patient.symptoms %}
                        <option value="{{ s.symptom_id }}">{{ s.symptom_id }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
    </div>

    <section class="w-75 m-auto pt-5 pb-3">
        <a class="btn btn-outline-info" type="submit"
           href="/sendToPrediction/{{ patient.id }}-{{ patient.nameOfPatient }}">Vytvořit predikci pomocí NS</a>
        <a class="btn btn-outline-info" type="submit"
           href="/sendToPredictionExpertSystem/{{ patient.id }}-{{ patient.nameOfPatient }}">Vytvořit predikci
            pomocí NS
            a experního systému</a>
    </section>

    {% if results != None %}
        {% include "result/resultsForPaginationOnPatient.html" %}
    {% endif %}
{% endblock content %}

emphysema/templates/patient/patients.html
{% extends "layout.html" %}

{% block content %}
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category,message in messages %}
                <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    <section class="w-75 m-auto pt-3">
    <a class="btn btn-outline-info" type="submit" href="{{ url_for('patientsBp.registerNewPatient') }}">Registrace nového pacienta
        <i class="bi bi-person-plus-fill"></i></a>
        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">ID</th>
                <th scope="col">Jméno pacienta</th>
                <th scope="col">Výsleky</th>
                <th scope="col">Akce</th>
            </tr>
            </thead>
            <tbody>
            {% for patient in patients.items %}
                <tr>
                    <th scope="row">{{ loop.index }}</th>
                    <th scope="row" id="id">{{ patient.id }}</th>
                    <td>{{ patient.nameOfPatient }}</td>
                    <td><a class="justify-content-center"
                           href="{{ url_for('patientsBp.patient',id=patient.id ~'-'~patient.nameOfPatient ) }}#resultsTable">Zobrazit</a></td>
                    <td class="">
                        <a href=" {{ url_for('patientsBp.patient',id=patient.id ~'-'~patient.nameOfPatient ) }}"
                           class="bi bi-info-square icons"></a>
                        <a href="{{ url_for('patientsBp.updatePatient',id=patient.id ~'-'~patient.nameOfPatient ) }}"
                           class="bi bi-pencil-square icons"></a>
                        <a href="{{ url_for('patientsBp.remove_patient',id=patient.id ~'-'~patient.nameOfPatient ) }}"
                           class="bi bi-trash icons"></a>

                    </td>
                </tr>
            {% endfor %}

            </tbody>
        </table>

    </section>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if patients.prev_num %}
                <li class="page-item">
                    <a class="page-link" href="{{ url_for('patientsBp.patients',page=patients.prev_num) }}"
                       tabindex="-1">Previous</a>
                </li>
            {% endif %}

            {% for page_number in patients.iter_pages() %}
                {% if page_number and patients.pages != 1 %}
                    {% if patients.page == page_number %}
                        <li class="page-item active">
                            <a class="page-link"
                               href="{{ url_for('patientsBp.patients',page=page_number) }}">{{ page_number }}</a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link"
                               href="{{ url_for('patientsBp.patients',page=page_number) }}">{{ page_number }}</a>
                        </li>
                    {% endif %}
                {% endif %}
            {% endfor %}

            {% if patients.next_num %}
                <li class="page-item">
                    <a class="page-link" href="{{ url_for('patientsBp.patients',page=patients.next_num) }}">Next</a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endblock %}

emphysema/templates/patient/registerNewPatient.html
{% extends "layout.html" %}
{% block content %}
    <div class="w-50 m-auto mt-5">
        <form method="post">
            {{ form.hidden_tag() }}
            <fieldset class="form-group m-2 ">
                <legend class="border-bottom mb-4">{{ legend }}</legend>
                <div class="form-group">
                    {{ form.nameOfPatient.label(class="form-control-label") }}
                    {% if form.nameOfPatient.errors %}
                        {{ form.nameOfPatient(class="form-control is-invalid form-control-lg is-invalid") }}
                        <div class="">
                            {% for error in form.nameOfPatient.errors %}
                                <div class="alert alert-danger">{{ error }}</div>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.nameOfPatient(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.height.label(class="form-control-label") }}
                    {% if form.height.errors %}
                        {{ form.height(class="form-control is-invalid form-control-lg is-invalid") }}
                        <div class="">
                            {% for error in form.height.errors %}
                                <div class="alert alert-danger">{{ error }}</div>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.height(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.weight.label(class="form-control-label") }}
                    {% if form.weight.errors %}
                        {{ form.weight(class="form-control is-invalid form-control-lg  is-invalid") }}
                        <div class="">
                            {% for error in form.weight.errors %}
                                <div class="alert alert-danger">{{ error }}</div>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.weight(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.age.label(class="form-control-label") }}
                    {% if form.age.errors %}
                        {{ form.age(class="form-control is-invalid form-control-lg  is-invalid") }}
                        <div class="">
                            {% for error in form.age.errors %}
                                <div class="alert alert-danger">{{ error }}</div>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.age(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group mt-3 mb-3">
                    {{ form.smoker.label(class="form-control-label") }}
                    {% if form.smoker.data == True %}
                        {{ form.smoker(checked=checked ,class="form-check form-check-lg") }}
                    {% else %}
                        {{ form.smoker(class="form-check form-check-lg") }}
                    {% endif %}
                </div>
                <div id="cigarettes" class="form-group">
                    {{ form.cigarets_per_year.label(class="form-control-label") }}
                    {% if form.cigarets_per_year.errors %}
                        {{ form.cigarets_per_year(class="form-control is-invalid form-control-lg  is-invalid") }}
                        <div class="">
                            {% for error in form.cigarets_per_year.errors %}
                                <div class="alert alert-danger">{{ error }}</div>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.cigarets_per_year(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.breath_frequency.label(class="form-control-label") }}
                    {% if form.breath_frequency.errors %}
                        {{ form.breath_frequency(class="form-control is-invalid form-control-lg  is-invalid") }}
                        <div class="">
                            {% for error in form.breath_frequency.errors %}
                                <div class="alert alert-danger">{{ error }}</div>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.breath_frequency(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div id="collapsingAdvancedMenu" class="btn btn-outline-info">Zobrazit pokročilé nastavení</div>
                <div class="advancedMenu" style="display: none">
                    <div class="card card-body">
                        <div class="form-group">
                            {{ form.pulse_oxymetry.label(class="form-control-label") }}
                            {% if form.pulse_oxymetry.errors %}
                                {{ form.pulse_oxymetry(class="form-control is-invalid form-control-lg  is-invalid") }}
                                <div class="">
                                    {% for error in form.pulse_oxymetry.errors %}
                                        <div class="alert alert-danger">{{ error }}</div>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.pulse_oxymetry(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.ptf_fev1.label(class="form-control-label") }}
                            {% if form.ptf_fev1.errors %}
                                {{ form.ptf_fev1(class="form-control is-invalid form-control-lg  is-invalid") }}
                                <div class="">
                                    {% for error in form.ptf_fev1.errors %}
                                        <div class="alert alert-danger">{{ error }}</div>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.ptf_fev1(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.ptf_fcv.label(class="form-control-label") }}
                            {% if form.ptf_fcv.errors %}
                                {{ form.ptf_fcv(class="form-control is-invalid form-control-lg  is-invalid") }}
                                <div class="">
                                    {% for error in form.ptf_fcv.errors %}
                                        <div class="alert alert-danger">{{ error }}</div>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.ptf_fcv(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.ptf_dlco.label(class="form-control-label") }}
                            {% if form.ptf_dlco.errors %}
                                {{ form.ptf_dlco(class="form-control is-invalid form-control-lg  is-invalid") }}
                                <div class="">
                                    {% for error in form.ptf_dlco.errors %}
                                        <div class="alert alert-danger">{{ error }}</div>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.ptf_dlco(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                        <div class="form-group mt-3 mb-3">
                            {{ form.deficit_alfa_1.label(class="form-control-label") }}
                            {% if form.deficit_alfa_1.data == True %}
                                {{ form.deficit_alfa_1(checked=checked ,class="form-check form-check-lg") }}
                            {% else %}
                                {{ form.deficit_alfa_1(class="form-check form-check-lg") }}
                            {% endif %}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group w-45">
                        {{ form.otherDiseases.label(class="form-control-label") }}
                        {% if form.otherDiseases.errors %}
                            {{ form.otherDiseases(class="form-control is-invalid form-control-lg  is-invalid") }}
                            <div class="">
                                {% for error in form.otherDiseases.errors %}
                                    <div class="alert alert-danger">{{ error }}</div>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.otherDiseases(class="form-control form-control-lg h-15em") }}
                        {% endif %}
                    </div>
                    <div class="form-group w-45">
                        {{ form.symptoms.label(class="form-control-label") }}
                        {% if form.symptoms.errors %}
                            {{ form.symptoms(class="form-control is-invalid form-control-lg  is-invalid") }}
                            <div class="">
                                {% for error in form.symptoms.errors %}
                                    <div class="alert alert-danger">{{ error }}</div>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.symptoms(class="form-control form-control-lg h-15em") }}
                        {% endif %}
                    </div>
                </div>
            </fieldset>
            <div class="form-group m-2">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>

    </div>
{% endblock content %}