emphysema/diseases/controller.py
import logging

from flask import Blueprint, render_template, flash, redirect, url_for, request
from flask_login import login_required

from emphysema.diseases.facade import DiseaseFacade
from emphysema.diseases.froms import DiseaseForm
from emphysema.diseases.manager import DiseaseService
from emphysema.services.crudService import BaseService
from emphysema.services.utils import getIdFromUrl
from emphysema.routes import Diseases, DiseasesForUrl, DiseaseCreate

diseasesBp = Blueprint('diseasesBp', __name__)


baseService = BaseService()
diseaseService = DiseaseService()
diseaseFacade = DiseaseFacade()

@diseasesBp.route('/diseases')
@login_required
def diseases():
    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per_page', 20, type=int)
    diseases_form_db = diseaseService.get_paged_diseases(page=page,per_page=per_page)
    return render_template(Diseases, title="Nemoci", diseases=diseases_form_db)


@diseasesBp.route('/createDisease', methods=['GET', 'POST'])
@login_required
def create_disease():
    form = DiseaseForm()
    if form.validate_on_submit():
        try:
            diseaseFacade.create_disease(form=form)
            flash(f'Nemoc {form.name_of_disease.data} vytvořen úspěšně', 'success')
        except Exception as e:
            flash(f'Během vytváření nemoci {form.name_of_disease.data} vznikla chyba, '
                  f'zkontrolujte, zdali daná nemoc již neexistuje.', 'danger')
            logging.error(e)
        finally:
            return redirect(url_for('diseasesBp.diseases'))
    return render_template(DiseaseCreate, title="Vytvoření nemoci", form=form)


@diseasesBp.route('/removeDisease/<id>')
@login_required
def remove_disease(id):
    diseaseService.remove(id=getIdFromUrl(id))
    return redirect(url_for(DiseasesForUrl))

emphysema/patients/controller.py
from flask import Blueprint, render_template, flash, redirect, url_for, request
from flask_login import login_required

from emphysema import db
from emphysema.diseases.model import Disease, DiseaseToPatient
from emphysema.diseases.manager import DiseaseService
from emphysema.patients.facade import PatientFacade
from emphysema.patients.froms import PatientForm
from emphysema.patients.model import Patient
from emphysema.patients.manager import PatientService
from emphysema.results.service import get_result_for_patient, get_results
from emphysema.services.utils import getIdFromUrl
from emphysema.services.crudService import BaseService
from emphysema.symptoms.model import Symptom, SymptomToPatient
from emphysema.symptoms.manager import SymptomService

patientsBp = Blueprint('patientsBp', __name__)

patientsService = PatientService()
diseaseService = DiseaseService()
symptomService = SymptomService()
baseService = BaseService()
patientFacade = PatientFacade()


@patientsBp.route('/patients')
@login_required
def patients():
    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per_page', 20, type=int)
    patients = patientsService.get_paged_patients(page=page, per_page=per_page)
    return render_template("patient/patients.html", title="Pacienti", patients=patients)


@patientsBp.route('/patient/<id>')
@login_required
def patient(id):
    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per_page', 20, type=int)
    patient_detail = patientsService.get_by_id(class_=Patient, id=getIdFromUrl(id))
    results = get_result_for_patient(id, page, per_page)
    return render_template("patient/patient.html", title="Pacienti", patient=patient_detail, results=results)


@patientsBp.route('/patient/resultPaged')
@login_required
def pagedResultsForPatient():
    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per_page', 20, type=int)
    results = get_results(page, per_page)
    return render_template("result/resultsForPaginationOnPatient.html", results=results)


@patientsBp.route('/registerNewPatient', methods=['GET', 'POST'])
@login_required
def registerNewPatient():
    form = PatientForm()
    if form.validate_on_submit():
        patientFacade.crete_new_patient(form=form)
        flash(f'Pacient {form.nameOfPatient.data} vytvořen úspěšně', 'success')
        return redirect(url_for('patientsBp.patients'))
    patientFacade.populate_data_for_form_register(form=form)
    return render_template("patient/registerNewPatient.html",
                           title="Registrace nového pacienta",
                           form=form,
                           button="Vytvořit uživatele",
                           legend="Nový pacient"
                           )


@patientsBp.route('/registerNewPatient/<id>', methods=['GET', 'POST'])
@login_required
def updatePatient(id):
    form = PatientForm()
    if form.validate_on_submit():
        patientFacade.update_patient(form=form,id=getIdFromUrl(id))
        flash(f'Pacient {form.nameOfPatient.data} aktualizován úspěšně', 'success')
        return redirect(url_for('patientsBp.patients'))

    patientFacade.populate_data_for_form_update(form=form,id=getIdFromUrl(id))
    patientFacade.populate_data_for_form_register(form=form)
    return render_template("patient//registerNewPatient.html",
                           title="Aktualizace pacienta",
                           form=form,
                           button="Aktualizovat uživatele",
                           legend="Aktualizace pacienta")


@patientsBp.route('/removePatient/<id>')
@login_required
def remove_patient(id):
    patientsService.remove(getIdFromUrl(id))
    flash(f'Pacient úspěšně smazán', 'success')
    return redirect(url_for('patientsBp.patients'))

emphysema/results/controller.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_required

from emphysema.diseases.manager import DiseaseService
from emphysema.patients.facade import PatientFacade
from emphysema.patients.manager import PatientService
from emphysema.patients.model import Patient
from emphysema.results.facade import ResultFacade
from emphysema.results.froms import SendToPredictionExpertSystem, SendToPredcitionForm
from emphysema.results.service import get_results, get_x_ray_to_result
from emphysema.services.crudService import BaseService
from emphysema.services.utils import getIdFromUrl, getNameFromUrl
from emphysema.symptoms.manager import SymptomService

resultsBp = Blueprint('resultsBp', __name__)

baseService = BaseService()
patientsService = PatientService()
diseaseService = DiseaseService()
symptomService = SymptomService()
resultFacade = ResultFacade()
patientFacade = PatientFacade()


@resultsBp.route('/results')
@login_required
def results():
    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per_page', 20, type=int)
    results_paged = get_results(page, per_page)
    return render_template("result/results.html", title="Výsledky", results=results_paged)


@resultsBp.route('/result_x_ray/<id>')
@login_required
def result_x_ray(id):
    result = get_x_ray_to_result(id=id)
    if result.generatedName:
        path_to_xray = '/static/x_rays/' + result.generatedName
        return render_template("result/x_ray.html", image=path_to_xray, old_image_name=result.originalName)
    else:
        return render_template("result/no_x_ray_image.html")


@resultsBp.route('/sendToPrediction/<id>', methods=['GET', 'POST'])
@login_required
def send_to_prediction(id):
    patient_id = getIdFromUrl(id)
    form = SendToPredcitionForm(patient_id=patient_id)
    patient = baseService.get_by_id(Patient, patient_id)
    if form.validate_on_submit():
        result = resultFacade.send_to_prediction(form=form, id=patient_id)
        if result:
            return redirect(url_for('patientsBp.patient', id=patient_id))
        else:
            flash(f'Pacient {patient.nameOfPatient} nebyl úspěšně odeslán k predikci', 'danger')
            return redirect(url_for('patientsBp.patient', id=patient_id))
    return render_template("prediction/sendToPrediction.html", title="Predikce", form=form,
                           patient_id=getNameFromUrl(id)[1], nameOfPatient=patient.nameOfPatient)


@resultsBp.route('/sendToPredictionExpertSystem/<id>', methods=['GET', 'POST'])
@login_required
def send_to_prediction_expert_system(id):
    idFromUrl = getIdFromUrl(id)
    form = SendToPredictionExpertSystem()
    patient = baseService.get_by_id(class_=Patient, id=idFromUrl)
    if form.validate_on_submit():
        patientFacade.update_patient(form=form, id=getIdFromUrl(id))
        resultFacade.send_to_prediction_expert_system(patient=patient, id=idFromUrl, form=form)
        flash(f'Pacient {form.nameOfPatient.data} byl úspěšně odeslán k predikci', 'success')
        return redirect(url_for('patientsBp.patient', id=idFromUrl))
    resultFacade.prepare_data_for_form(form=form, id=idFromUrl, patient=patient)
    return render_template("prediction/sendToPredictionExpertSystem.html",
                           title="Predikce pomoci expertního systému a NS",
                           form=form, patient_id=idFromUrl)

emphysema/users/controller.py
import secrets

from flask import Blueprint, redirect, render_template, url_for
from flask_login import login_user, logout_user, login_required

from emphysema import db
from emphysema.users.froms import LoginForm, UserForm
from emphysema.users.model import User

usersBp = Blueprint('usersBp', __name__)


@usersBp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(password=form.hashed_login.data).first()
        if user:
            login_user(user=user, remember=form.remember.data)
            return redirect(url_for('main.index'))
    return render_template("login.html", title="Login", form=form)


@usersBp.route('/createUser', methods=['GET', 'POST'])
@login_required
def saveUser():
    form = UserForm()
    if form.validate_on_submit():
        # hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.user_name.data, email=str(secrets.token_hex(2)), password=form.password.data)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('main.index'))
    form.password.data = str(secrets.token_hex(32))
    return render_template("createUser.html", title="Vytvoření uživtele", form=form)


@usersBp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('usersBp.login'))

emphysema/templates/createUser.html
{% extends 'layout.html' %}

{% block content %}
    <div class="w-50 m-auto mt-5">
        <form method="post">
            {{ form.hidden_tag() }}
            <fieldset class="form-group m-2 ">
                <legend class="border-bottom mb-4">Nový uživatel</legend>
                <div class="form-group">
                    {{ form.user_name.label(class="form-control-label") }}
                    {% if form.user_name.errors %}
                        {{ form.user_name(class="form-control is-invalid form-control-lg is-invalid") }}
                        <div class="">
                            {% for error in form.user_name.errors %}
                                <div class="alert alert-danger">{{ error }}</div>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.user_name(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control is-invalid form-control-lg is-invalid") }}
                        <div class="">
                            {% for error in form.password.errors %}
                                <div class="alert alert-danger">{{ error }}</div>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg", readonly="readonly") }}
                    {% endif %}
                    <div class="text-danger">Heslo si prosím opište a zašlete danému uživateli</div>
                </div>
            </fieldset>
            <div class="form-group m-2">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>

    </div>


{% endblock %}

emphysema/templates/home.html
{% extends "layout.html" %}

emphysema/templates/layout.html
<!DOCTYPE html>
<html lang="cs">
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link rel="stylesheet" type="text/css" href="../static/custom.css">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
            crossorigin="anonymous"></script>
    <script type="application/javascript" src="../static/ajax.js"></script>
    <title>{{ title }}</title>

</head>
<body>
<nav class="navbar navbar-expand-md navbar-light">
    <div class="container-fluid nav-tabs bg-light">
        <a class="navbar-brand" href="/">Emphysema</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link {{ 'active' if patients else '' }} "
                           href="{{ url_for('patientsBp.patients') }}">Pacienti

                            <i class="bi bi-people-fill"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {{ 'active' if results else '' }}" href="{{ url_for('resultsBp.results') }}">Výsledky
                            <i class="bi bi-bar-chart-fill"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {{ 'active' if diseases else '' }}" aria-current="page"
                           href="{{ url_for('diseasesBp.diseases') }}">Nemoci
                            <i class="bi bi-file-medical-fill"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {{ 'active' if symptoms else '' }}" aria-current="page"
                           href="{{ url_for('symptomBp.symptoms') }}">Symptomy
                            <i class="bi bi-file-medical-fill"></i>
                        </a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link " href="#" id="navbarDropdownMenuLink" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false" aria-haspopup="true">
                            Nastavení
                            <i class="bi bi-sliders"></i>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <li><a class="dropdown-item" href="{{ url_for('patientsBp.registerNewPatient') }}">Registrace
                                nového pacienta
                                <i class="bi bi-person-plus-fill"></i>
                            </a></li>
                            <div class="dropdown-divider"></div>
                            <li><a class="dropdown-item" href="{{ url_for('usersBp.saveUser') }}">Vytvoření uživtele
                                <i class="bi bi-person-plus-fill"></i>
                            </a></li>
                            <div class="dropdown-divider"></div>
                            <li><a class="dropdown-item" href="{{ url_for('diseasesBp.create_disease') }}">Vytvoření
                                nemoci
                                <i class="bi bi-file-earmark-plus-fill"></i>
                            </a></li>
                            {#                            <li><a class="dropdown-item" href="/createSymptom">Vytvoření symptomu#}
                            {#                                <i class="bi bi-file-earmark-plus-fill"></i>#}
                            {#                            </a></li>#}
                            <div class="dropdown-divider"></div>
                            <li><a class="dropdown-item" href="{{ url_for('usersBp.logout') }}">Odhlášení
                                <i class="bi bi-box-arrow-right"></i>
                            </a></li>
                        </ul>
                    </li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>
<div class="height100">
    {% block content %}{% endblock %}
</div>
<footer>
    Emphysema project UHK 2020/2021
</footer>
</body>
</html>

emphysema/templates/login.html
{% extends 'layout.html' %}
{% block content %}
<div class="w-50 m-auto mt-5">
    <form method="post">
        {{ form.hidden_tag() }}
        <fieldset class="form-group m-2 ">
            <legend class="border-bottom mb-4">Přihlášení</legend>
            <div class="form-group">
                {{ form.hashed_login.label(class="form-control-label") }}
                {% if form.hashed_login.errors %}
                    {{ form.hashed_login(class="form-control is-invalid form-control-lg is-invalid") }}
                    <div class="">
                        {% for error in form.hashed_login.errors %}
                            <div class="alert alert-danger">{{ error }}</div>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.hashed_login(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.remember.label(class="form-control-label") }}
                {% if form.remember.errors %}
                    {{ form.remember(class="form-control is-invalid form-control-lg is-invalid") }}
                    <div class="">
                        {% for error in form.remember.errors %}
                            <div class="alert alert-danger">{{ error }}</div>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.remember(class="") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group m-2">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock %}